- name: Ensure the database directory exists
  file:
    path: "{{ ara_server_database_name | basename }}"
    state: directory
    owner: "{{ ara_server_user }}"
    group: "{{ ara_server_group }}"
    mode: 0750

- become: yes
  become_user: ara
  block:
    - name: Run SQL migrations
      environment:
        ARA_SETTINGS: "{{ ara_server_settings }}"
        PATH: "{{ path_with_virtualenv | default(omit) }}"
      command: ara-manage migrate
