---
- name: Set up pre-requirements
  include_tasks: pre-requirements.yaml

- name: Set up ara-server
  include_tasks: ara_server/main.yaml
  when: ara_server_install | bool

- name: Include ara-web installation
  include_tasks: ara_web/main.yaml
  when: ara_web_install | bool

- name: Include web server installation
  include_tasks: "webserver/{{ ara_webserver }}.yaml"
