- name: Fail fast if running Python <3.6 for ara-server
  fail:
    msg: "Python >=3.6 is required to run ara-server"
  when:
    - ansible_python_version is version("3.6", "<")
    - ara_server_install

- name: Include OS family/distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"

- become: true
  block:
    - name: Install required packages
      package:
        name: "{{ ara_required_packages }}"
        state: present

    - name: Create user for ara
      user:
        name: "{{ ara_user }}"
        comment: User for ARA Records Ansible
        shell: /sbin/nologin
        home: "{{ ara_home_dir }}"

    - name: Ensure required directories are created with the right permissions
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ara_user }}"
        group: "{{ ara_group }}"
        mode: 0750
      loop:
        - "{{ ara_home_dir }}"
        - "{{ ara_config_dir }}"
        - "{{ ara_log_dir }}"
