- name: Fail pre-emptively if running Python <3.6
  fail:
    msg: "Python >=3.6 is required to run ara-server"
  when: ansible_python_version is version("3.6", "<")

- name: Include OS family/distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"

- become: true
  block:
    - name: Install required packages
      package:
        name: "{{ ara_server_required_packages }}"
        state: present

    - name: Create user for ara-server
      user:
        name: "{{ ara_server_user }}"
        comment: User for ARA Records Ansible
        shell: /sbin/nologin
        home: "{{ ara_server_home_dir }}"

    - name: Ensure required directories are created with the right permissions
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ara_server_user }}"
        group: "{{ ara_server_group }}"
        mode: 0750
      loop:
        - "{{ ara_server_home_dir }}"
        - "{{ ara_server_base_dir }}"
        - "{{ ara_server_config_dir }}"
        - "{{ ara_server_log_dir }}"
