- when: ansible_os_family == "Debian"
  become: yes
  block:
    - name: Install apt-transport-https
      package:
        name: apt-transport-https
        state: present

    - name: Install nodesource repository key
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

    - name: Install nodesource apt source repository
      apt_repository:
        repo: "deb-src https://deb.nodesource.com/node_{{ ara_web_nodejs_version }}.x {{ ansible_distribution_release }} main"
        state: present

    - name: Install nodesource apt repository
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ ara_web_nodejs_version }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

- when: ansible_os_family == "RedHat"
  block:
    - name: Install Nodesource yum repository
      become: yes
      package:
        name: "https://rpm.nodesource.com/pub_{{ ara_web_nodejs_version }}.x/fc/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-fc{{ ansible_distribution_major_version }}-1.noarch.rpm"
        state: present

- name: Install nodejs
  become: yes
  package:
    name: nodejs
    state: present
